name: Mainnet

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  mainnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm ci
      - run: npm run test -- MainnetService.test